### ISSUE TITLE
Error No static method registerReceiver

### ISSUE THREAD

**Issue by Vofchuk** [zelloptt/zello-android-client-sdk#92]
Hello,

I am trying to integrate the Zello Android SDK into a Flutter app. My Flutter app is a clean project with no other plugins or packages, only the Zello SDK. However, I am encountering the following runtime error:

```
E/AndroidRuntime(19825): FATAL EXCEPTION: main
E/AndroidRuntime(19825): Process: com.example.ptt_test, PID: 19825
E/AndroidRuntime(19825): java.lang.NoSuchMethodError: No static method registerReceiver(Landroid/content/Context;Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;I)Landroid/content/Intent; in class Landroidx/core/content/ContextCompat; or its super classes (declaration of 'androidx.core.content.ContextCompat' appears in /data/app/~~nYKXDnbG9pjorwFd5GPzmA==/com.example.ptt_test-T6iW4u82qbTXHaNPuknnwA==/base.apk)
E/AndroidRuntime(19825): 	at com.zello.sdk.Sdk.registerAppStateReceivers(Sdk.java:799)
E/AndroidRuntime(19825): 	at com.zello.sdk.Sdk.connect(Sdk.java:991)
E/AndroidRuntime(19825): 	at com.zello.sdk.Sdk.onCreate(Sdk.java:92)
E/AndroidRuntime(19825): 	at com.zello.sdk.Zello.doConfigure(Zello.java:1118)
E/AndroidRuntime(19825): 	at com.zello.sdk.Zello.configure(Zello.java:70)
E/AndroidRuntime(19825): 	at com.example.ptt_test.MainActivity.onCreate(MainActivity.kt:16)
E/AndroidRuntime(19825): 	at android.app.Activity.performCreate(Activity.java:8595)
E/AndroidRuntime(19825): 	at android.app.Activity.performCreate(Activity.java:8573)
E/AndroidRuntime(19825): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
E/AndroidRuntime(19825): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
E/AndroidRuntime(19825): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
E/AndroidRuntime(19825): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(19825): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/AndroidRuntime(19825): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
```

This is my MainActivity.kt:

```
package com.example.ptt_test

import io.flutter.embedding.android.FlutterActivity
import android.os.Bundle
import androidx.annotation.NonNull
import io.flutter.plugin.common.MethodChannel
import com.zello.sdk.Zello
import io.flutter.embedding.engine.FlutterEngine


class MainActivity: FlutterActivity() {
    private val CHANNEL = "com.example.ptt_test/zello"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Zello.getInstance().configure(this)
    }


}
```

Steps to Reproduce:
Created a new Flutter project.
Added the Zello SDK .aar file to the android/app/libs folder.
Modified android/app/build.gradle to include the Zello SDK as a dependency.
Implemented Zello SDK initialization and method channel in MainActivity.kt.
Ran the app on an Android device.
Expected Behavior:
The app should run without errors, and I should be able to use the Zello SDK features.

Actual Behavior:
The app crashes at runtime with the aforementioned java.lang.NoSuchMethodError.

I'm not so familiar with Android development, can someone help me fix this issue?

**Comment by zello-eugene** [comment]
Would you try adding the `androidx.core:core` dependency to you project, i.e.:
```
dependencies {
	implementation "androidx.core:core:1.12.0"
}
```

**Comment by Vofchuk** [comment]
Hello, I adde implementation "androidx.appcompat:appcompat:1.6.1" and it worked (adding 1.12.0 gave me another error

Daniel Vofchuk

Co-Founder & CEO

***@***.*** ( ***@***.*** )

+972 58 724 8685

www.vizo.dev ( http://www.vizo.dev/ )

**Comment by zello-eugene** [comment]
Out of curiosity, what was the error that you saw when using 1.12.0?
